version: '3'
services: 
    zookeeper:
        container_name: zookeeper
        build: 
            context: ./zookeeper/
            dockerfile: Dockerfile
        environment: 
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports: 
            - "2181:2181"

    kafka:
        container_name: kafka
        build: 
            context: ./kafka/
            dockerfile: Dockerfile
        depends_on: 
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#        env_file: 
#            - ./.env
        ports: 
            - "9092:9092"

#    kafka-rest-proxy:
#        container_name: kafka-rest-proxy
#        build: 
#            context: ./kafka/kafka_rest_proxy/
#            dockerfile: Dockerfile
#        depends_on: 
#            - zookeeper
#            - kafka
#        ports: 
#            - "8082:8082"
#        env_file: 
#            - ./.env

#    kafka-ui:
#        container_name: kafka_ui
#        build: 
#            context: ./kafka/kafka_ui/
#            dockerfile: Dockerfile
#        depends_on: 
#            - kafka
#            - kafka-rest-proxy
#        ports: 
#            - "8000:8000"
#        env_file: 
#            - ./.env

    producer:
        container_name: producer
        depends_on:
            - zookeeper
            - kafka
        command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9092 python3 main.py"
        environment:
            KAFKA_BROKER_URL: kafka:9092
            TRANSACTIONS_TOPIC: queueing.transactions
            TRANSACTIONS_PER_SECOND: 10
        build: 
            context: ./producer/
            dockerfile: Dockerfile

#    spark-master:
#        container_name: spark-master
#        build: 
#            context: ./spark-master/
#            dockerfile: Dockerfile
#        ports: 
#            - "8080:8080"
#            - "7077:7077"
    
#    spark-worker:
#        container_name: spark-worker
#        depends_on: 
#            - spark-master
#        build: 
#            context: ./spark-worker/
#            dockerfile: Dockerfile
#        environment: 
#            - SPARK_MASTER=spark://spark-master:7077
#        ports: 
#            - "8081:8081"
    
    consumer:
        container_name: consumer
        depends_on:
            - zookeeper
            - kafka
        command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9092 python3 main.py"
        build: 
            context: ./consumer/
            dockerfile: Dockerfile
        environment:
            KAFKA_BROKER_URL: kafka:9092
            TRANSACTIONS_TOPIC: queueing.transactions
#        links: 
#            - spark-master:spark-master
