version: '3'
services: 
    zookeeper:
        container_name: zookeeper
        build: 
            context: ./zookeeper/
            dockerfile: Dockerfile
        ports: 
            - "2181:2181"

    kafka:
        container_name: kafka
        depends_on: 
            - zookeeper
        build: 
            context: ./kafka/
            dockerfile: Dockerfile
        env_file: 
            - ./.env
        ports: 
            - "9092:9092"

    producer:
        container_name: producer
        depends_on:
            - zookeeper
            - kafka
        build: 
            context: ./producer/
            dockerfile: Dockerfile

    spark-master:
        container_name: spark-master
        build: 
            context: ./spark-master/
            dockerfile: Dockerfile
        ports: 
            - "8080:8080"
            - "7077:7077"
    
    spark-worker:
        container_name: spark-worker
        depends_on: 
            - spark-master
        build: 
            context: ./spark-worker/
            dockerfile: Dockerfile
        environment: 
            - SPARK_MASTER=spark://spark-master:7077
        ports: 
            - "8081:8081"
    
    consumer:
        container_name: consumer
        build: 
            context: ./consumer/
            dockerfile: Dockerfile
        links: 
            - spark-master:spark-master
